// <auto-generated />
using System;
using ControlPanelConcerts.ContextDb;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace APIConcert.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20210428082556_pruebaclase")]
    partial class pruebaclase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ControlPanelConcerts.Models.Concierto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("FechaConcierto")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreConcierto")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Concierto");
                });

            modelBuilder.Entity("ControlPanelConcerts.Models.ConciertoMusico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ConciertoId")
                        .HasColumnType("int");

                    b.Property<int>("MusicoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ConciertoId");

                    b.HasIndex("MusicoId");

                    b.ToTable("ConciertoMusico");
                });

            modelBuilder.Entity("ControlPanelConcerts.Models.Instrumento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("MarcaInstrumento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreInstrumento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PrecioInstrumento")
                        .HasColumnType("int");

                    b.Property<string>("TipoInstrumento")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Instrumento");
                });

            modelBuilder.Entity("ControlPanelConcerts.Models.Musico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("datetime2");

                    b.Property<int>("InstrumentoId")
                        .HasColumnType("int");

                    b.Property<string>("NombreMusico")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SueldoMusico")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InstrumentoId");

                    b.ToTable("Musico");
                });

            modelBuilder.Entity("ControlPanelConcerts.Models.ConciertoMusico", b =>
                {
                    b.HasOne("ControlPanelConcerts.Models.Concierto", "Concierto")
                        .WithMany()
                        .HasForeignKey("ConciertoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ControlPanelConcerts.Models.Musico", "Musico")
                        .WithMany()
                        .HasForeignKey("MusicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Concierto");

                    b.Navigation("Musico");
                });

            modelBuilder.Entity("ControlPanelConcerts.Models.Musico", b =>
                {
                    b.HasOne("ControlPanelConcerts.Models.Instrumento", "Instrumento")
                        .WithMany()
                        .HasForeignKey("InstrumentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instrumento");
                });
#pragma warning restore 612, 618
        }
    }
}
